package Modelo;
// Generated Jan 26, 2017 8:52:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Butaca generated by hbm2java
 */
public class Butaca  implements java.io.Serializable {


     private Integer idButaca;
     private Sala sala;
     private boolean libre;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Butaca() {
    }

	
    public Butaca(boolean libre) {
        this.libre = libre;
    }
    public Butaca(Sala sala, boolean libre, Set<Reserva> reservas) {
       this.sala = sala;
       this.libre = libre;
       this.reservas = reservas;
    }
   
    public Integer getIdButaca() {
        return this.idButaca;
    }
    
    public void setIdButaca(Integer idButaca) {
        this.idButaca = idButaca;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public boolean isLibre() {
        return this.libre;
    }
    
    public void setLibre(boolean libre) {
        this.libre = libre;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


