package Modelo;
// Generated Feb 6, 2017 5:25:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargos generated by hbm2java
 */
public class Cargos  implements java.io.Serializable {


     private Integer idCargo;
     private String nomCargo;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Cargos() {
    }

	
    public Cargos(String nomCargo) {
        this.nomCargo = nomCargo;
    }
    public Cargos(String nomCargo, Set<Empleado> empleados) {
       this.nomCargo = nomCargo;
       this.empleados = empleados;
    }
   
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public String getNomCargo() {
        return this.nomCargo;
    }
    
    public void setNomCargo(String nomCargo) {
        this.nomCargo = nomCargo;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


