package Modelo;
// Generated Jan 26, 2017 8:52:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private Integer idPersona;
     private String dni;
     private String nombre;
     private String apellidos;
     private Integer telefono;
     private String usuario;
     private String password;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Personas() {
    }

	
    public Personas(String dni, String nombre, String apellidos, String usuario, String password) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.usuario = usuario;
        this.password = password;
    }
    public Personas(String dni, String nombre, String apellidos, Integer telefono, String usuario, String password, Set<Cliente> clientes, Set<Empleado> empleados) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.usuario = usuario;
       this.password = password;
       this.clientes = clientes;
       this.empleados = empleados;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


