package Modelo;
// Generated Jan 26, 2017 8:52:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Poblacion generated by hbm2java
 */
public class Poblacion  implements java.io.Serializable {


     private Integer idPoblacion;
     private String nomPoblacion;
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
     private Set<Cine> cines = new HashSet<Cine>(0);

    public Poblacion() {
    }

	
    public Poblacion(String nomPoblacion) {
        this.nomPoblacion = nomPoblacion;
    }
    public Poblacion(String nomPoblacion, Set<Proveedor> proveedors, Set<Cine> cines) {
       this.nomPoblacion = nomPoblacion;
       this.proveedors = proveedors;
       this.cines = cines;
    }
   
    public Integer getIdPoblacion() {
        return this.idPoblacion;
    }
    
    public void setIdPoblacion(Integer idPoblacion) {
        this.idPoblacion = idPoblacion;
    }
    public String getNomPoblacion() {
        return this.nomPoblacion;
    }
    
    public void setNomPoblacion(String nomPoblacion) {
        this.nomPoblacion = nomPoblacion;
    }
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }
    public Set<Cine> getCines() {
        return this.cines;
    }
    
    public void setCines(Set<Cine> cines) {
        this.cines = cines;
    }




}


