package Modelo;
// Generated Feb 6, 2017 5:25:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private Poblacion poblacion;
     private Integer cif;
     private String nombre;
     private Integer telefono;
     private Integer cp;
     private Set<Cabecerapedido> cabecerapedidos = new HashSet<Cabecerapedido>(0);

    public Proveedor() {
    }

    public Proveedor(Poblacion poblacion, Integer cif, String nombre, Integer telefono, Integer cp, Set<Cabecerapedido> cabecerapedidos) {
       this.poblacion = poblacion;
       this.cif = cif;
       this.nombre = nombre;
       this.telefono = telefono;
       this.cp = cp;
       this.cabecerapedidos = cabecerapedidos;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Poblacion getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(Poblacion poblacion) {
        this.poblacion = poblacion;
    }
    public Integer getCif() {
        return this.cif;
    }
    
    public void setCif(Integer cif) {
        this.cif = cif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }
    public Set<Cabecerapedido> getCabecerapedidos() {
        return this.cabecerapedidos;
    }
    
    public void setCabecerapedidos(Set<Cabecerapedido> cabecerapedidos) {
        this.cabecerapedidos = cabecerapedidos;
    }




}


