package Modelo;
// Generated Jan 26, 2017 8:52:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sesion generated by hbm2java
 */
public class Sesion  implements java.io.Serializable {


     private Integer idSesion;
     private Pelicula pelicula;
     private Sala sala;
     private Date fecha;
     private Date hora;
     private Float precio;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Sesion() {
    }

    public Sesion(Pelicula pelicula, Sala sala, Date fecha, Date hora, Float precio, Set<Reserva> reservas) {
       this.pelicula = pelicula;
       this.sala = sala;
       this.fecha = fecha;
       this.hora = hora;
       this.precio = precio;
       this.reservas = reservas;
    }
   
    public Integer getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(Integer idSesion) {
        this.idSesion = idSesion;
    }
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


